#estagio 1 - base
FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
RUN mkdir /app
WORKDIR /app
EXPOSE 80/tcp

#estagio 2 - publish
FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS publish
WORKDIR /app
COPY mvc1.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c Release -o dist

#estagio 3 - final
FROM base AS final
WORKDIR /dist
COPY --from=publish /app/dist .
ENTRYPOINT [ "dotnet", "mvc1.dll" ]