FROM mcr.microsoft.com/dotnet/core/sdk:2.2
RUN mkdir /app
WORKDIR /app
COPY mvc1.csproj .
RUN dotnet restore
COPY . .
RUN dotnet publish -c Release -o dist
EXPOSE 80/tcp
CMD [ "dotnet", "dist/mvc1.dll" ]